import os
import sys


# add path for getting autodoc
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

project = 'Green MBTools'
html_title = 'Green MBTools'

copyright = '2023-2026, Green-Phys'
author = 'Gaurav Harsha, Chia-Nan Yeh, Sergei Iskakov, Vibin Abraham, Pavel Pokhilko'
from green_mbtools.version import __version__ as release  # noqa: E402


def _generate_versions_list():
    """Regenerate ``_versions.rst`` (the "older versions" list on the landing
    page) so it never needs manual editing.

    ``release`` (the version being built, sourced from ``version.py``) is
    always shown as ``(latest)`` and points at the site root. Previously
    published *stable* releases are listed below, each pointing at its
    ``/v<version>`` snapshot on the gh-pages branch. Pre-releases are omitted
    from the list -- the only pre-release ever shown is the current one, when
    ``release`` itself is a pre-release.

    The set of already-published versions is supplied by the docs workflow via
    the ``DOC_EXISTING_VERSIONS`` env var (whitespace-separated gh-pages
    directory names, e.g. ``v1.0.0a0``). For local builds it is usually unset,
    so only the current version is listed.
    """
    from packaging.version import InvalidVersion, Version

    base_url = "https://Green-Phys.github.io/green-mbtools"

    def _bare(name):
        return name[1:] if name.startswith("v") else name

    current = _bare(release)
    names = set(os.environ.get("DOC_EXISTING_VERSIONS", "").split())
    names.add(release)

    older = []
    for name in names:
        bare = _bare(name)
        if bare == current:
            continue
        try:
            if Version(bare).is_prerelease:
                continue
        except InvalidVersion:
            continue
        older.append(bare)

    older.sort(key=Version, reverse=True)

    lines = [f"* `{current} (latest) <{base_url}>`_"]
    lines += [f"* `{ver} <{base_url}/v{ver}>`_" for ver in older]

    out_path = os.path.join(os.path.dirname(__file__), "_versions.rst")
    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


_generate_versions_list()  # noqa: E305

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',       # For Google/NumPy-style docstrings
    'sphinx.ext.viewcode',       # Adds source code links
    'myst_parser',               # for markdown
    'sphinx_autodoc_typehints',  # Better type hint rendering
]

# ``_versions.rst`` is generated by ``_generate_versions_list`` and pulled in
# via ``.. include::`` on the landing page, so it is not a standalone document.
exclude_patterns = ['_versions.rst']



# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# html_theme = 'pydata_sphinx_theme'
html_theme = 'furo'
html_logo = "rosetta.png"
html_favicon = "rosetta.png"
html_static_path = ['_static']
html_css_files = ['custom.css']
